### PR TITLE
Subpackage

### PR DESCRIPTION
**Pull request by StefanMewa**
Moved module to a subpackage to resolve name clash with `backports.os` when importing `os`.

`backports.os`: https://github.com/pjdelport/backports.os

### CODE REVIEW

**Comment by PiDelport** [comment]
Note: PR #3 may make this unnecessary?

**Comment by StefanMewa** [comment]
Most certainly it's simpler, which is a huge advantage.

I tried to follow the guideline on original `backports` project (https://pypi.org/project/backports/ section `Building your own backports module`) which suggests to create a subpackage per project. Many `backports` projects have similar issues and aligning them to common template seems like a step in good direction.

What do you think?

**Comment by PiDelport** [comment]
@StefanMewa: That's a good question.

I interpreted the guideline you linked to be mainly about the namespace-support code required in `backports/__init__.py`, rather than about whether a sub-package is present, or not, specifically.

That said, following a common convention would certainly be a good idea! I'm just not sure what exactly the convention should be?

**Comment by StefanMewa** [comment]
@pjdelport I won't surprise you (it's what this PR is about after all) - I'd say the regular `package/subpackage` structure. Citing the `backports` again:
> [...] First, set your project up like:
> ```
> project/
> project/setup.py
> project/backports/
> project/backports/__init__.py   <--- SPECIAL - see below!
> project/backports/yourpkg/
> project/backports/yourpkg/__init__.py
> project/backports/yourpkg/foo.py
> project/backports/yourpkg/bar.py
> ```
> 
> This places your own package inside of the backports namespace, so your package and its modules can be imported like this:
> 
> ```
> import backports.yourpkg
> import backports.yourpkg.foo
> ```

Author doesn't insist on it, true, but it does look like a preferred approach. Pro: It isolates your modules from other "backports" in a straightforward manner. Con: More code (but not too much really). Probably all about ones preference.

**Comment by minrk** [comment]
I agree with @pjdelport's interpretation of the example as not making any points about subpackages. I don't believe that example makes any argument that subpackages are preferred to modules. It happens to use an example involving multiple files, in which case a subpackage makes sense. For single-module backports, I don't see anything suggesting that using a subpackage would a preferred implementation.

> Pro: It isolates your modules from other "backports" in a straightforward manner.

`backports.shutil_which` is just as isolated as `backports.shutil_which.shutil_which`, is it not?

**Comment by StefanMewa** [comment]
By isolation I meant safe usage of absolute imports in your own module (this is where it all started). But as `from __future__ import absolute_import` gives the same result and is simpler, I agree this can be the way to go for single modules.

Maybe ambiguity of `backports` readme is indirectly the cause of all this fuss. Where there is a room left for interpretation there obviously will be more than one :) Clearly not the worst case, but still.

All in all, thanks for nice discussion. If there is no other voice willing to speak I'll close this PR next week.

/S

**Pull request closed without merging**
